name: "build"

on:
  push:
    branches:
      - main
      - 2.x
      - 3.x
    tags:
      - "*"
  release:
    types: [published]
  pull_request:
    branches:
      - main
      - 2.x
      - 3.x

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "0.16.1"
          verb: call
          args: --src . ci --ci --version ${{ github.ref_name }} --code-cove-token env:CODECOV_TOKEN --git-token env:GITHUB_TOKEN --registry-username env:REGISTRY_USERNAME --registry-password env:REGISTRY_PASSWORD --git-branch ${BRANCH_NAME} ${IS_TAG}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          IS_TAG: ${{ github.ref_type == 'tag' && '--is-tag' || '' }}
          BRANCH_NAME: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_type == 'tag' && 'main' || github.ref_name }}